# Generated by Django 3.2.5 on 2021-08-10 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Задается автоматически при обновлении записи.', verbose_name='Дата обновления записи')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ингредиента.', max_length=200, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Система измерений для ингредиента.', max_length=200, verbose_name='Система измерений')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Задается автоматически при обновлении записи.', verbose_name='Дата обновления записи')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Количество ингредиента.', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение должно быть не меньше 1')], verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Задается автоматически при обновлении записи.', verbose_name='Дата обновления записи')),
            ],
            options={
                'ordering': ('-ingredient',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта.', max_length=200, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Полное пошаговое описание рецепта.', verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(help_text='Время приготовления (в минутах).', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение должно быть больше 0')], verbose_name='Время приготовления')),
                ('image', models.ImageField(help_text='Картинка рецепта.', upload_to='recipes/images/', verbose_name='Картинка рецепта')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Задается автоматически при обновлении записи.', verbose_name='Дата обновления записи')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Задается автоматически при обновлении записи.', verbose_name='Дата обновления записи')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тэга.', max_length=200, unique=True, verbose_name='Название тэга')),
                ('color', models.CharField(help_text='Цвет в HEX.', max_length=200, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(help_text='Техническое название тэга.', max_length=200, unique=True, verbose_name='Техническое название тэга')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Задается автоматически при обновлении записи.', verbose_name='Дата обновления записи')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
