# Generated by Django 3.2.5 on 2021-08-02 07:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ингредиента.', max_length=200, unique=True, verbose_name='Название ингредиента.')),
                ('measurement_unit', models.CharField(help_text='Система измерений.', max_length=200, verbose_name='Система измерений.')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта.', max_length=200, verbose_name='Название рецепта.')),
                ('text', models.TextField(help_text='Описание рецепта.', verbose_name='Описание рецепта.')),
                ('cooking_time', models.IntegerField(help_text='Время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение должно быть больше 0')], verbose_name='Время приготовления')),
                ('image', models.ImageField(help_text='Картинка рецепта.', upload_to='media', verbose_name='Картинка рецепта')),
                ('author', models.ForeignKey(help_text='Автор рецепта.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ForeignKey(help_text='Ингридиенты к рецепту', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient', verbose_name='Ингридиент')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тэга.', max_length=200, verbose_name='Название тэга.')),
                ('color', models.CharField(help_text='Цвет в HEX.', max_length=200, verbose_name='Цвет тэга.')),
                ('slug', models.SlugField(help_text='Техническое название тэга', max_length=200, verbose_name='Техническое название тэга')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Автор листа покупок.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recipe', models.ForeignKey(help_text='Рецепт из листа покупок.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ForeignKey(help_text='Тэги рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.tag', verbose_name='Тэги'),
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Автор листа избранного.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recipe', models.ForeignKey(help_text='Рецепт из листа избранного.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_shopping_list'),
        ),
        migrations.AddConstraint(
            model_name='favoritelist',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_favorite_list'),
        ),
    ]
