# Generated by Django 3.2.5 on 2021-08-02 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название системы исчесления.', max_length=200, unique=True, verbose_name='Название системы исчесления.')),
                ('short_name', models.CharField(help_text='Короткое название системы исчесления.', max_length=10, unique=True, verbose_name='Название системы исчесления.')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_unit',
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Количество ингредиента', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Значение должно быть не меньше 0')], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(help_text='Ингреденет необходимый для рецепта.', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredientunit', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(help_text='Рецепт для которого используются ингреденеты.', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.AddConstraint(
            model_name='measurementunit',
            constraint=models.UniqueConstraint(fields=('name', 'short_name'), name='unique_measurement_unit'),
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингридиент используемый единцу исчесления.', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_unit', to='recipes.ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='measurement_unit',
            field=models.ForeignKey(help_text='Система измерений для ингредиента', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_unit', to='recipes.measurementunit', verbose_name='Система измерений'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(help_text='Ингридиенты к рецепту', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredientunit', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт из листа покупок.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='recipes.recipeingredients', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredientunit',
            constraint=models.UniqueConstraint(fields=('ingredient', 'measurement_unit'), name='unique_ingredient_unit'),
        ),
    ]
