# Generated by Django 3.2.5 on 2021-08-10 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Количество ингредиента.', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Значение должно быть не меньше 1')], verbose_name='Количество'),
        ),
    ]
