# Generated by Django 3.2.5 on 2021-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email пользователя', max_length=254, unique=True, verbose_name='Email адрес'),
        ),
    ]
